In [86]:
import os
from typing import Tuple

import numpy as np
import pandas as pd

from tqdm.auto import tqdm

import torch
from torch import nn

from sklearn.preprocessing import KBinsDiscretizer

from utils.data_utils import global_context, split_data, weekends, global_context_emb_avg
from utils.config_utils import DataConf, ModelConf, ClassificationParamsConf
from datamodules import TransactionRNNDataModule
from datamodules.preprocessing import data_preprocessing
from utils.config_utils import get_config_with_dirs

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [87]:
(data_conf, model_conf, learning_conf, params_conf), _ = get_config_with_dirs('config.ini')

original_df, (train_sequences, val_sequences, test_sequences) = data_preprocessing(
    data_conf,
    model_conf,
    params_conf
)

  0%|          | 0/490513 [00:00<?, ?it/s]

Preparing gc from embedding layer:   0%|          | 0/19 [00:00<?, ?it/s]

  0%|          | 0/5000 [00:00<?, ?it/s]

In [55]:
train_sequences

small_group  \
client_id                                                      
1700             [10, 10, 3, 142, 3, 2, 3, 3, 3, 3, 3, 3, 3]   
902        [22, 2, 22, 97, 2, 3, 1, 1, 1, 22, 1, 3, 2, 61...   
1820       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 205, 3, 3, 3...   
721        [23, 3, 3, 13, 22, 13, 22, 3, 13, 3, 22, 22, 1...   
1842       [26, 39, 13, 3, 55, 16, 2, 40, 40, 43, 46, 16,...   
...                                                      ...   
4227       [25, 78, 27, 5, 27, 19, 2, 27, 3, 27, 2, 14, 2...   
558        [3, 3, 25, 2, 2, 2, 71, 71, 2, 58, 5, 5, 43, 2...   
9679       [78, 78, 78, 78, 53, 78, 78, 78, 78, 78, 78, 7...   
2023       [2, 2, 63, 68, 68, 4, 2, 4, 17, 2, 2, 27, 19, ...   
7702       [73, 22, 2, 2, 22, 22, 26, 22, 29, 16, 55, 3, ...   

                                                  amount_rur  \
client_id                                                      
1700       [37, 50, 48, 47, 47, 2, 46, 50, 49, 50, 49, 49...   
902        [33, 33, 17, 11, 28, 44, 21, 18, 15, 19, 16, 5...   
1820       [50, 36, 42, 50, 50, 20, 20, 20, 20, 20, 49, 3...   
721        [29, 31, 43, 19, 10, 14, 18, 31, 18, 31, 13, 1...   
1842       [24, 46, 17, 48, 46, 48, 38, 44, 44, 44, 43, 4...   
...                                                      ...   
4227       [35, 35, 33, 35, 15, 27, 35, 13, 43, 24, 29, 1...   
558        [6, 6, 40, 38, 27, 22, 29, 34, 19, 24, 19, 28,...   
9679       [2, 2, 2, 39, 1, 1, 4, 3, 3, 7, 2, 7, 7, 17, 3...   
2023       [16, 12, 23, 33, 33, 16, 42, 30, 22, 34, 14, 2...   
7702       [6, 27, 29, 11, 8, 9, 27, 12, 25, 48, 48, 46, ...   

                                                        hour  \
client_id                                                      
1700              [7, 8, 0, 6, 6, 0, 4, 10, 10, 6, 6, 0, 14]   
902        [0, 0, 0, 0, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1820       [7, 7, 11, 7, 7, 11, 11, 11, 11, 11, 11, 0, 7,...   
721        [0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
1842       [0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...   
...                                                      ...   
4227       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
558        [8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
9679       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2023       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
7702       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0,...   

                                                         day  \
client_id                                                      
1700          [12, 6, 11, 3, 3, 5, 5, 18, 18, 20, 20, 24, 7]   
902        [27, 28, 29, 29, 31, 4, 5, 6, 6, 7, 7, 9, 9, 9...   
1820       [21, 21, 21, 22, 23, 27, 27, 27, 27, 27, 27, 2...   
721        [1, 1, 1, 3, 3, 3, 4, 5, 5, 6, 6, 7, 7, 9, 9, ...   
1842       [19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 2...   
...                                                      ...   
4227       [6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 9, 9, 9, 10, 10...   
558        [23, 23, 24, 24, 24, 24, 25, 25, 25, 26, 26, 2...   
9679       [6, 11, 11, 11, 12, 16, 16, 16, 16, 17, 17, 17...   
2023       [7, 10, 10, 10, 10, 11, 11, 11, 12, 13, 14, 14...   
7702       [13, 13, 13, 15, 15, 16, 16, 16, 17, 17, 17, 1...   

                                                 day_of_week  \
client_id                                                      
1700                 [5, 0, 5, 0, 0, 2, 2, 3, 3, 5, 5, 2, 2]   
902        [5, 6, 0, 0, 2, 6, 0, 1, 1, 2, 2, 4, 4, 4, 5, ...   
1820       [2, 2, 2, 3, 4, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, ...   
721        [5, 5, 5, 0, 0, 0, 1, 2, 2, 3, 3, 4, 4, 6, 6, ...   
1842       [4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 0, 0, 0, ...   
...                                                      ...   
4227       [3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 6, 6, 6, 0, 0, ...   
558        [4, 4, 5, 5, 5, 5, 6, 6, 6, 0, 0, 0, 1, 1, 1, ...   
9679       [1, 6, 6, 6, 0, 4, 4, 4, 4, 5, 5, 5, 0, 0, 1, ...   
2023       [4

In [88]:
datamodule = TransactionRNNDataModule(
    train_sequences,
    val_sequences,
    test_sequences,
    params_conf,
    learning_conf
)

In [89]:
a = next(iter(datamodule.train_dataloader()))

In [85]:
a[-1].shape

torch.Size([128, 401, 16])

In [50]:
avg_amnt_seqs = []
avg_mcc_seqs = []
for seq in tqdm(train_sequences.iloc, total=train_sequences.shape[0]):
    amnt_seq = []
    mcc_seq = []

    for i in seq['gc_id']:
        amnt_seq.append(gc_emb_amnt[i])
        mcc_seq.append(gc_emb_mcc[i])
    avg_amnt_seqs.append(amnt_seq)
    avg_mcc_seqs.append(mcc_seq)

  0%|          | 0/3804 [00:00<?, ?it/s]

In [51]:
train_sequences['amnt_avg_embed'] = avg_amnt_seqs

In [52]:
train_sequences.iloc[0]['amnt_avg_embed']

[array([-0.14871599,  0.19030489, -0.46283162, -0.34657732, -0.24200143,
        -0.18323986,  0.06345016, -0.40866023]),
 array([-0.09616771,  0.21815494, -0.41340044, -0.37405574, -0.25912285,
        -0.20399565,  0.09143222, -0.418614  ]),
 array([-0.10876427,  0.2172938 , -0.42839098, -0.3649483 , -0.24618533,
        -0.20384894,  0.08288978, -0.42031041]),
 array([-0.10876427,  0.2172938 , -0.42839098, -0.3649483 , -0.24618533,
        -0.20384894,  0.08288978, -0.42031041]),
 array([-0.10876427,  0.2172938 , -0.42839098, -0.3649483 , -0.24618533,
        -0.20384894,  0.08288978, -0.42031041]),
 array([-0.10876427,  0.2172938 , -0.42839098, -0.3649483 , -0.24618533,
        -0.20384894,  0.08288978, -0.42031041]),
 array([-0.10876427,  0.2172938 , -0.42839098, -0.3649483 , -0.24618533,
        -0.20384894,  0.08288978, -0.42031041]),
 array([-0.08864156,  0.22401129, -0.41461539, -0.38022062, -0.24510355,
        -0.20337507,  0.09225266, -0.4231846 ]),
 array([-0.08864156,  0.